# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: step 1 - checkout from github
        uses: actions/checkout@v2

      - name: step 2 - set up JDK 1.8 
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: step 3 - build Maven project
        run: mvn -B package --file pom.xml
        
      - name: step 4 - list the current directory
        run: ls -a
        
      - name: step 5 - what's in the target folder ?
        run: |
          cd target
          ls -a
        

